fubi-client/Models/User.cs
using static System.Runtime.InteropServices.JavaScript.JSType;

namespace fubi_client.Models
{
    public class User
    {
        public string? id_usuario { get; set; }
        public string? cedula { get; set; }
        public string? nombre { get; set; }
        public string? primer_apellido { get; set; }
        public string? segundo_apellido { get; set; }
        public string? telefono { get; set; } 
        public Date? fecha_nacimiento { get; set; } 
        public short? rol { get; set; }
        public bool activo { get; set; } = true;

    }


}

fubi-client/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Mvc;

namespace fubi_client.Controllers
{
    public class DashboardController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

fubi-client/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace fubi_client.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult CreateUser()
        {
            return View();
        }


    }
}

fubi-client/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;

namespace fubi_client.Controllers
{
    public class UserController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult CreateUser()
        {
            return View();
        }
    }
}

fubi-client/Views/Dashboard/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section Styles {
    <link rel="stylesheet" href="~/css/dashboard.css" />
}

<section class="p-3">
    <div class="bg-inicio">
        <h2 class="titulo-logeo">¡Bienvenido, Himalaya!</h2>
    </div>
    <div class="row">
        <div class="col-sm-12 col-md-4">
            <div class="card">
                <div class="card-body d-flex flex-column justify-content-center align-items-center">
                    <i class="fa-solid fa-wallet"></i>
                    <h3>₡2,300,000</h3>
                    <p>Dinero recaudado</p>
                </div>
            </div>
        </div>
        <div class="col-sm-12 col-md-4">
            <div class="card">
                <div class="card-body d-flex flex-column justify-content-center align-items-center">
                    <i class="fa-solid fa-handshake-simple"></i>
                    <h3>40</h3>
                    <p>Artículos prestados</p>
                </div>
            </div>
        </div>
        <div class="col-sm-12 col-md-4">
            <div class="card">
                <div class="card-body d-flex flex-column justify-content-center align-items-center">
                    <i class="fa-solid fa-hands-holding-child"></i>
                    <h3>595</h3>
                    <p>Beneficiarios</p>
                </div>
            </div>
        </div>

    </div>

</section>

fubi-client/Views/Home/Index.cshtml
@{
    Layout = "~/Views/Shared/Public_Layout.cshtml";
}

<div class="d-lg-flex half">
    <div class="bg order-1 order-md-2"
         style="background-image: url('/images/young-adult-helping-disabled-friend.jpg');"></div>
    <div class="contents order-2 order-md-1">
        <div class="container">
            <div class="row align-items-center justify-content-center">
                <div class="col-md-7">
                    <div class="d-flex justify-content-center mb-4">
                    <img src="https://root-projects.s3.amazonaws.com/FUBIREDIP.png" class="fubi-logo" alt="Alternate Text" />
                    </div>
                    <p class="mb-4">
                        ¡Bienvenidos a FUBIREDIP! Por favor, inicia sesión para acceder a tu cuenta.
                    </p>
                    <form action="#" method="post">
                        <div class="form-group first">
                            <label for="correo">Correo electrónico</label>
                            <input type="text"
                                   class="form-control"
                                   placeholder="ejemplo@correo.com"
                                   id="correo" />
                        </div>
                        <div class="form-group mb-3">
                            <label for="contrasena">Contraseña</label>
                            <div class="el-hechicero d-flex align-items-center">
                                <input type="password"
                                       class="form-control"
                                       placeholder="Ingrese su contraseña"
                                       id="contrasena" />
                                <a><ion-icon name="eye-outline"></ion-icon></a>
                            </div>
                        </div>

                        <div class="d-flex mb-3 mt-3">
                            <a href="@Url.Action("CreateUser", "Home")" class="mx-1 mt-1 mb-1">¿Olvidaste tu contraseña?</a>
                            <a href="@Url.Action("Index", "Dashboard")">Sinlogin</a>  
                        </div>        
                        <input type="submit" class="btn-acceder text-center" value="Acceder" />
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

fubi-client/Views/Shared/Public_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Fubiredip</title>
    <meta charset="utf-8" />
    <meta name="viewport"
          content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="description" content="" />
    <meta name="keywords" content="" />
    <meta name="author" content="Phoenixcoded" />
    <!-- Favicon icon -->
    <link rel="icon" href="~/images/fubi-logo.png" type="image/x-icon" />
    <link rel="stylesheet" href="~/css/login.css" />
    <link rel="stylesheet" href="~/dist/css/plugins/bootstrap.min.css" />
    @RenderSection("Styles", required: false)
</head>
<body>
    <div class="pcoded-main-container">
        @RenderBody()
   </div>

    <!-- Required Js -->
    <script src="~/dist/js/plugins/bootstrap.min.js"></script>
    <script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

fubi-client/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Fubiredip</title>
    <meta charset="utf-8" />
    <meta name="viewport"
          content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="description" content="" />
    <meta name="keywords" content="" />
    <meta name="author" content="Phoenixcoded" />
    <!-- Favicon icon -->
    <link rel="icon" href="~/images/fubi-logo.png" type="image/x-icon" />

    <!-- vendor css -->
    <link rel="stylesheet" href="~/css/style.css" />
    <link href="~/dist/css/plugins/bootstrap.min.css" rel="stylesheet" />
    <link href="~/dist/css/plugins/perfect-scrollbar.css" rel="stylesheet" />
    <link href="~/dist/css/plugins/prism-coy.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/app.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/2.1.8/css/dataTables.bootstrap5.css" />
    @RenderSection("Styles", required: false)
</head>
<body>
    <!-- [ Pre-loader ] start -->
    <div class="loader-bg">
        <div class="loader-track">
            <div class="loader-fill"></div>
        </div>
    </div>
    <!-- [ Pre-loader ] End -->
    <!-- [ navigation menu ] start -->
    <nav class="pcoded-navbar" style="background-color: #1e1e1e">
        <div class="navbar-wrapper">
            <div class="navbar-content scroll-div">
                <div class="">
                    <div class="main-menu-header" style="background-color: #9aba99">
                       <img class="img-radius"
                             src="~/images/img-profile.jpg"
                              alt="User-Profile-Image" />
                        <div class="user-details" id="more-details">
                            <!--Aquí va el nombre del viejo-->
                            <span class="text-dark">Jose Pablo Solís Rodríguez</span>
                            <!--Aquí va el rol-->
                            <div class="text-dark">
                                Administrador<ion-icon name="chevron-down-outline"></ion-icon>
                            </div>
                        </div>
                    </div>
                    <div class="collapse" id="nav-user-link">
                        <ul class="list-unstyled nav-icons">
                            <li class="list-group-item">
                                <a href="user-profile.html"><ion-icon name="settings-outline"></ion-icon>Mi perfil</a>
                            </li>
                            <li class="list-group-item">
                                <a href="auth-normal-sign-in.html"><ion-icon name="log-out-outline"></ion-icon>Cerrar sesión</a>
                            </li>
                        </ul>
                    </div>
                </div>

                <ul class="nav pcoded-inner-navbar">
                    <li class="nav-item pcoded-menu-caption">
                        <label>Navigation</label>
                    </li>
                    <li class="nav-item">
                        <a href="@Url.Action("Index", "Dashboard")" class="nav-link">
                            <span class="pcoded-micon"><ion-icon name="home-outline"></ion-icon></span><span class="pcoded-mtext">Inicio</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="@Url.Action("Index", "User")" class="nav-link">
                            <span class="pcoded-micon"><ion-icon name="person-outline"></ion-icon></span><span class="pcoded-mtext">Usuarios</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="#!" class="nav-link">
                            <span class="pcoded-micon"><ion-icon name="gift-outline"></ion-icon></span><span class="pcoded-mtext">Donaciones</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="#!" class="nav-link">
                            <span class="pcoded-micon"><ion-icon name="people-outline"></ion-icon></span><span class="pcoded-mtext">Beneficiarios</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="#!" class="nav-link">
                            <span class="pcoded-micon"><ion-icon name="folder-open-outline"></ion-icon></span><span class="pcoded-mtext">Inventario</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="#!" class="nav-link">
                            <span class="pcoded-micon"><ion-icon name="document-text-outline"></ion-icon></i></span><span class="pcoded-mtext">Préstamos</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="#!" class="nav-link">
                            <span class="pcoded-micon"><ion-icon name="wallet-outline"></ion-icon></span><span class="pcoded-mtext">Ingresos</span>
                        </a>
                    </li>
                   
                </ul>
            </div>
        </div>
    </nav>
    <!-- [ navigation menu ] end -->
    <!-- [ Header ] start -->
    <header class="navbar pcoded-header navbar-expand-lg" style="background-color: #1e1e1e">
        <div class="m-header">
            <a href="#!" class="b-brand">
                <img src="~/images/fubi-logo.png" alt="" class="fubi-icon"/>
                <h1 class="text-light fubi-title">FUBIREDIP</h1>
            </a>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="navbar-nav mr-auto">
                <li>
                    <a class="mobile-menu" id="mobile-collapse" href="#!"><span></span></a>
                </li>
            </ul>
        </div>
    </header>
    <!-- [ Header ] end -->
    <!-- [ Main Content ] start -->
    <div class="pcoded-main-container">
        @RenderBody()
        <!-- [ Main Content ] end -->
    </div>

    <!-- Required Js -->
    <script src="~/dist/js/vendor-all.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

    <script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>
    <script src="~/dist/js/pcoded.min.js"></script>
    <script src="~/dist/js/uikit.min.js"></script>
    <script src="https://unpkg.com/feather-icons"></script>
    <script src="https://cdn.datatables.net/2.1.8/js/dataTables.js"></script>
    <script src="https://cdn.datatables.net/2.1.8/js/dataTables.bootstrap5.js"></script>
    <script src="https://kit.fontawesome.com/4ccaae5e72.js" crossorigin="anonymous"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

fubi-client/Views/User/CreateUser.cshtml
@model fubi_client.Models.User

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section Scripts {
    <script src="~/js/User.js"></script>
}

@section Styles {
    <link rel="stylesheet" href="~/css/user.css" />
}

<section class="p-3">
    @if (ViewBag.Mensaje != null)
    {
        <div class="alert alert-secondary text-center">@ViewBag.Mensaje</div>
    }

    <h2>Crear Nuevo Usuario</h2>
    <div class="d-flex flex-column rounded-circle justify-content-center align-items-center">
        <img id="profilePic" src="~/images/no-profile-pic-icon-27.webp" width="200px" alt="Profile picture overview" />
        <p>Prevista imagen del perfil</p>
    </div>

    <form asp-action="CrearCuenta" asp-controller="Login">


        <div class="mb-3">
            <label class="form-label">Identificación<span class="campos-requeridos">*</span></label>
            <input type="text" asp-for="cedula" class="form-control"
                   onkeyup="ConsultarNombre();">
        </div>

        <div class="mb-3">
            <label class="form-label">Nombre<span class="campos-requeridos">*</span></label>
            <input type="text" asp-for="nombre" class="form-control">
        </div>
        <div class="mb-3">
            <label class="form-label">Primer Apellido<span class="campos-requeridos">*</span></label>
            <input type="text" asp-for="nombre" class="form-control">
        </div>
        <div class="mb-3">
            <label class="form-label">Segundo Apellido<span class="campos-requeridos">*</span></label>
            <input type="text" asp-for="nombre" class="form-control">
        </div>
        <div class="mb-3">
            <label class="form-label">Teléfono<span class="campos-requeridos">*</span></label>
            <input type="text" asp-for="nombre" class="form-control">
        </div>
        <div class="mb-3">
            <label class="form-label">Fecha de nacimiento<span class="campos-requeridos">*</span></label>
            <input type="date" asp-for="nombre" class="form-control">
        </div>
        <label for="rol">Rol<span class="campos-requeridos">*</span></label>
        <select id="rol" class="form-control" name="rol">
            <option value="admin">Administrador</option>
            <option value="user">Usuario</option>
            <option value="editor">Editor</option>
        </select>
        <div class="pt-3 form-group">
            <label for="userImage">Selecciona una imagen de perfil</label>
            <input type="file" class="form-control-file" id="userImage" onchange="previewImage(event)">
        </div>
        <div class="pt-3">
            <input type="submit" class="btn btn-success btn-md mr-2" value="Crear Usuario">
            <a href="@Url.Action("Index", "User")" class="btn btn-danger text-light btn-md">Cancelar</a>
        </div>
    </form>
</section>

fubi-client/Views/User/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section Scripts {
    <script src="~/js/User.js"></script>
}

<div class="card">
    <div class="card-body">
        <div class="d-flex justify-content-between">
        <h5 class="card-title">Lista de Usuarios</h5>
            <a href="@Url.Action("CreateUser", "User")" class="btn-insertar">Crear Usuario</a>
        </div>
        <div class="table-responsive">
            <table id="user-table" class="table text-nowrap align-middle mb-0">
                <thead>
                    <tr class="border-2 border-bottom border-primary border-0">
                        <th>#</th>
                        <th>Identificación</th>
                        <th>Nombre</th>
                        <th>Correo</th>
                        <th>Rol</th>
                        <th>Acciones</th>
                    </tr>
                </thead>
                <tbody class="table-group-divider">

                </tbody>
            </table>
        </div>
    </div>
</div>